apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celloscope-pvc
  namespace: celloscope
  labels:
    app: celloscope 
spec:
  storageClassName: nfs-athene
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi


